### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by anonymiz** [syounger/yt-mp3#1]
iam getting blank page

**Comment by syounger** [comment]
What URL are you using?

**Comment by anonymiz** [comment]
what url , do i need to change any settings

**Comment by syounger** [comment]
Well, where did you get a blank page? What are you trying to do?

**Comment by anonymiz** [comment]
https://anonymiz.com/youtube-to-mp3-downloader/
from index.php

**Comment by syounger** [comment]
That is not an endpoint which this API provides. I do not know how you got that URL.

**Comment by anonymiz** [comment]
i copied the whole script to root folder , how to use this script

**Comment by syounger** [comment]
This code provides a very basic API, as explained in the README. It is NOT intended for production.

If you are planning to provide a public service for youtube-to-mp3 you will have to be able to write your own script.
